# Generated by Django 5.2.17 on 2026-08-31 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['name'], 'permissions': [('retire_equipment', 'Can retire equipment')]},
        ),
    ]
