# Generated by Django 5.2.17 on 2026-09-10 10:52

import django.db.models.deletion
import organizations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_location_equipment_application_equipment_brand_and_more'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='organization',
            field=models.ForeignKey(default=organizations.models.default_organization, on_delete=django.db.models.deletion.PROTECT, related_name='equipments', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='location',
            name='organization',
            field=models.ForeignKey(default=organizations.models.default_organization, on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AddConstraint(
            model_name='equipment',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_equipment_code_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_location_name_per_organization'),
        ),
    ]
