# Generated by Django 5.2.17 on 2026-09-12 03:17

import django.db.models.deletion
import django.utils.timezone
import organizations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_equipment_organization_location_organization_and_more'),
        ('organizations', '0005_organization_account_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='equipment_type',
            field=models.CharField(choices=[('industrial', 'Industrial'), ('automotive', 'Automotriz')], default='industrial', max_length=20),
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meter_readings', to='equipment.equipment')),
                ('organization', models.ForeignKey(default=organizations.models.default_organization, on_delete=django.db.models.deletion.PROTECT, related_name='meter_readings', to='organizations.organization')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meter_readings_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'lectura de medidor',
                'verbose_name_plural': 'lecturas de medidores',
                'ordering': ['-recorded_at', '-pk'],
            },
        ),
    ]
