# Generated by Django 5.2.17 on 2026-09-13 07:54

import django.db.models.deletion
import organizations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_equipment_equipment_type_meterreading'),
        ('organizations', '0006_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipments', to='organizations.customer'),
        ),
        migrations.CreateModel(
            name='EquipmentIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier_type', models.CharField(choices=[('license_plate', 'Patente'), ('vin', 'VIN'), ('chassis', 'Chasis'), ('engine', 'Número de motor'), ('other', 'Otro identificador')], max_length=20)),
                ('value', models.CharField(max_length=100)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identifiers', to='equipment.equipment')),
                ('organization', models.ForeignKey(default=organizations.models.default_organization, on_delete=django.db.models.deletion.PROTECT, related_name='equipment_identifiers', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'identificador de equipo',
                'verbose_name_plural': 'identificadores de equipo',
                'ordering': ['identifier_type', 'value'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'identifier_type', 'value'), name='unique_equipment_identifier_per_organization')],
            },
        ),
    ]
