# Generated by Django 5.2.17 on 2026-09-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_address_organization_business_line_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='rut',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
