# Generated by Django 5.2.17 on 2026-09-11 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_add_geography'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='account_status',
            field=models.CharField(choices=[('active', 'Activa'), ('demo', 'Demo'), ('read_only', 'Solo lectura'), ('suspended', 'Suspendida')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='demo_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='demo_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='subscription_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
