# Generated by Django 5.2.17 on 2026-09-13 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_organization_account_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('customer_type', models.CharField(choices=[('person', 'Persona natural'), ('company', 'Empresa')], max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'rut'), name='unique_customer_rut_per_organization')],
            },
        ),
    ]
