# Generated by Django 5.2.17 on 2026-09-10 10:52

import django.db.models.deletion
import organizations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_documentsequence_maintenancerecord_completed_at_and_more'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerecord',
            name='organization',
            field=models.ForeignKey(default=organizations.models.default_organization, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='organization',
            field=models.ForeignKey(default=organizations.models.default_organization, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='organizations.organization'),
        ),
    ]
