# Generated by Django 5.2.17 on 2026-09-12 03:17

import django.db.models.deletion
import django.utils.timezone
import organizations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_equipment_equipment_type_meterreading'),
        ('maintenance', '0004_maintenancerecord_organization_and_more'),
        ('organizations', '0005_organization_account_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerecord',
            name='meter_reading',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='MaintenancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('strategy', models.CharField(choices=[('time', 'Tiempo'), ('meter', 'Horómetro / kilometraje')], max_length=20)),
                ('interval_days', models.PositiveIntegerField(blank=True, null=True)),
                ('interval_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('active', models.BooleanField(default=True)),
                ('last_service_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_service_meter', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_plans_created', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_plans', to='equipment.equipment')),
                ('organization', models.ForeignKey(default=organizations.models.default_organization, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_plans', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'plan de mantenimiento',
                'verbose_name_plural': 'planes de mantenimiento',
                'ordering': ['equipment', 'name'],
            },
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='reset_plans',
            field=models.ManyToManyField(blank=True, related_name='reset_by_maintenances', to='maintenance.maintenanceplan'),
        ),
    ]
