# Generated by Django 5.2.17 on 2026-09-10 10:52

import django.db.models.deletion
import organizations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_assign_tecnicos_permissions'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='organization',
            field=models.ForeignKey(default=organizations.models.default_organization, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='organizations.organization'),
        ),
    ]
